version: "3.8"
services:
  backend:
    image: "joanna15202/springboot-react-fullstack:21.7.2021.7.5.29"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev